import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeProvider from "@/context/Theme";
import { Toaster } from "sonner";
import { SessionProvider } from "next-auth/react";
import { ReactNode } from "react";
import { auth } from "@/auth";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Hello next js",
  description: "Generated by create next app",
  icons:{
    icon : '/images/site-logo.svg'
  }
};

const RootLayout = async ({ children }: { children : ReactNode}) => {
   
  const session = await auth();

  return (
    <html lang="en" suppressHydrationWarning>
      <SessionProvider session={session}>
        <body
          className={`${inter.variable} antialiased`}
        >
          <ThemeProvider attribute="class" defaultTheme="system" enableSystem disableTransitionOnChange>
          
            {children}
          </ThemeProvider>
          <Toaster richColors/>
        </body>

      </SessionProvider>
    </html>
  );
}

export default RootLayout